### PR TITLE
Update README.md with instructions for local environment setup

### PR DESCRIPTION
**Pull request by balazsgaspar**
Added end-to-end example for local environment setup

### CODE REVIEW

**Review by wmudge — CHANGES_REQUESTED** [review]
I suggest we split this out into a separate file, like `DEVELOPMENT.md`.

**Comment by jimright** [comment]
@balazsgaspar, @wmudge - I've moved the instructions for local development to a DEVELOPMENT.md.
If you are happy with that change I will merged

**Comment by balazsgaspar** [comment]
@jimright I am ok with moving this to a separate file, just make sure we link to it from the README.md

**Review by jimright — APPROVED** [review]
Looks good. Approved.

**Pull request merged**
